using BlogWebAPI.Context;
using BlogWebAPI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Http.Results;

namespace BlogWebAPI.Controllers
{
    public class SetupController:ApiController
    {
        readonly DatabaseContext _context;

        static Author Kriss = new Author
        {
            AuthorId = 1,
            Name = "Kristaps",
            Description = "Hi, my name is Kristaps"
        };

        static BlogPost Post = new BlogPost
        {
            BlogPostId = 1,
            Title = "Example post",
            Summary = "This is an example post",
            Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
            AuthorId = Kriss.AuthorId,
            Author = Kriss,
            Tags = new string[]
            {
                "example",
                "post"
            }
        };

        public SetupController(DatabaseContext context)
        {
            _context = context;
        }

        // GET api/values
        [HttpGet]
        public IHttpActionResult Get()
        {
          
            if (!_context.Authors.Any())
            {
                _context.Authors.Add(Kriss);
                _context.BlogPosts.Add(Post);

                _context.SaveChanges();
            }


            //if (_context.Authors.Any())
            //    return "There's an author there: {_context.Authors.First().Name}";

            //return "No author there...";

            return Ok(true);
        }
    }
}
    